### ISSUE TITLE
getDailyGrids: cross-check dimensionality of response

### ISSUE THREAD

**Issue by llnelson** [IMDProjects/IM_Climate#38]

**Comment by BrentFrakes** [comment]
Here are the arguments for my call for OLYM:

{'bbox': '-124.73483637, 47.469495669,-123.121666491,48.2747212797',
 'eDate': '20160616',
 'elems': [{'duration': 'dly', 'interval': 'dly', 'name': 'mint', 'prec': 1}],
 'grid': 21,
 'meta': 'll',
 'sDate': '20160615'}

**Comment by llnelson** [comment]
And, here a JS request to ACIS for comparison:
var url = "http://data.rcc-acis.org/GridData",
    params = {
        bbox: "-124.734836369753, 47.4694956690073, -123.121666491032, 48.2747212797403",
        sdate: "2016-06-15",
        edate: "2016-06-15",
        grid: "21",
        elems: [{
            name: "maxt",
            interval: "dly",
            duration: "dly",
            "prec":1
        }],
        "image":{
        "width":450,
        "levels":[90,95,100,105,110]
        }
    };
postResults(url, params);

**Comment by BrentFrakes** [comment]
![image](https://cloud.githubusercontent.com/assets/5944919/19117498/6ea300ae-8ad6-11e6-918d-d8f99bd7f9ac.png)

This is what I am doing to validate my code. From what I can tell, I am doing things correctly.

1. Pull data using my code and convert to the ascii grid
2. Go to the PRISM site, download the grid for that day, and convert it from C to F 
3. Difference the grids.  Because of rounding issues, I am getting a variance of 0.05 F

**Comment by llnelson** [comment]
The output ASCII grids are registered to the centroid of the lower left pixel.
